sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
sonar.token=sqp_34bd93b5433f5f1fe104b8f78ea12624459a1326
sonar.projectKey=projet-exam-backend
sonar.projectName=projet-exam-backend

# Sources réelles uniquement (pas les tests, pas node_modules)
sonar.sources=src
sonar.tests=src/__tests__

# Exclusions du périmètre "source"
sonar.exclusions=**/node_modules/**,dist/**,src/__tests__/**

# Fichiers reconnus comme tests
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

# Rapport de couverture généré par Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info